//
// Created by Tyler Jaacks on 3/6/22.
//

#ifndef TESTPROJECT_TOKEN_H
#define TESTPROJECT_TOKEN_H

#include <string>

enum token_type {
    TOKEN_UNDEFINED = 0,

    TOKEN_EOF = 999,

    TOKEN_PREPROCESSOR_INCLUDE,
    TOKEN_PREPROCESSOR_DEFINE,
    TOKEN_PREPROCESSOR_UNDEF,
    TOKEN_PREPROCESSOR_IF_DEF,
    TOKEN_PREPROCESSOR_IF_N_DEF,
    TOKEN_PREPROCESSOR_IF,
    TOKEN_PREPROCESSOR_ELSE,
    TOKEN_PREPROCESSOR_ELIF,
    TOKEN_PREPROCESSOR_ENDIF,
    TOKEN_PREPROCESSOR_ERROR,
    TOKEN_PREPROCESSOR_PRAGMA,

    TOKEN_TYPE = 301,

    TOKEN_TYPE_MODIFIER_UNSIGNED,
    TOKEN_TYPE_MODIFIER_SIGNED,

    TOKEN_IDENTIFIER = 306,

    TOKEN_LITERAL_STRING = 305,
    TOKEN_LITERAL_NUMBER = 303,
    TOKEN_LITERAL_REAL = 304,
    TOKEN_LITERAL_CHAR = 302,

    TOKEN_SYMBOL_LEFT_PAREN = 40,
    TOKEN_SYMBOL_RIGHT_PAREN = 41,
    TOKEN_SYMBOL_LEFT_BRACKET = 91,
    TOKEN_SYMBOL_RIGHT_BRACKET = 93,

    TOKEN_SYMBOL_PLUS_SIGN = 43,
    TOKEN_SYMBOL_MINUS_SIGN = 45,
    TOKEN_SYMBOL_ASTERISK = 42,
    TOKEN_SYMBOL_FORWARD_SLASH = 47,
    TOKEN_SYMBOL_PERCENT_SIGN = 37,

    TOKEN_SYMBOL_EXCLAMATION_MARK = 33,
    TOKEN_SYMBOL_QUESTION_MARK = 63,
    TOKEN_SYMBOL_EQUAL_SIGN = 61,
    TOKEN_SYMBOL_LEFT_BRACE = 123,
    TOKEN_SYMBOL_RIGHT_BRACE = 125,

    TOKEN_SYMBOL_COLON = 58,
    TOKEN_SYMBOL_SEMICOLON = 59,
    TOKEN_SYMBOL_AMPERSAND = 38,
    TOKEN_SYMBOL_COMMA = 44,
    TOKEN_SYMBOL_PERIOD = 46,
    TOKEN_SYMBOL_PIPE = 124,

    TOKEN_SYMBOL_TILDE,

    TOKEN_KEYWORD_AUTO,
    TOKEN_KEYWORD_BREAK = 408,
    TOKEN_KEYWORD_CONST = 401,
    TOKEN_KEYWORD_CASE = 412,
    TOKEN_KEYWORD_CONTINUE = 409,
    TOKEN_KEYWORD_DEFAULT = 413,
    TOKEN_KEYWORD_DO = 405,
    TOKEN_KEYWORD_ELSE = 407,
    TOKEN_KEYWORD_ENUM,
    TOKEN_KEYWORD_EXTERN,
    TOKEN_KEYWORD_FOR = 403,
    TOKEN_KEYWORD_GOTO,
    TOKEN_KEYWORD_IF = 406,
    TOKEN_KEYWORD_REGISTER,
    TOKEN_KEYWORD_RETURN = 410,
    TOKEN_KEYWORD_SIZEOF,
    TOKEN_KEYWORD_STATIC,
    TOKEN_KEYWORD_STRUCT = 402,
    TOKEN_KEYWORD_SWITCH = 411,
    TOKEN_KEYWORD_TYPEDEF,
    TOKEN_KEYWORD_UNION,
    TOKEN_KEYWORD_VOLATILE,
    TOKEN_KEYWORD_WHILE = 404,

    TOKEN_SYMBOL_INCREMENT = 355,
    TOKEN_SYMBOL_DECREMENT = 356,

    TOKEN_SYMBOL_PLUS_ASSIGNMENT = 361,
    TOKEN_SYMBOL_MINUS_ASSIGNMENT = 362,
    TOKEN_SYMBOL_MULT_ASSIGNMENT = 363,
    TOKEN_SYMBOL_DIVIDE_ASSIGNMENT = 364,
    TOKEN_SYMBOL_MODULO_ASSIGNMENT,

    TOKEN_SYMBOL_CMP_NOT_EQUAL = 352,
    TOKEN_SYMBOL_CMP_EQUAL = 351,
    TOKEN_SYMBOL_CMP_LESS_THAN = 60,
    TOKEN_SYMBOL_CMP_LESS_THAN_EQUAL = 354,
    TOKEN_SYMBOL_CMP_GREATER_THAN = 62,
    TOKEN_SYMBOL_CMP_GREATER_THAN_EQUAL = 353,

    TOKEN_SYMBOL_CMP_OR = 357,
    TOKEN_SYMBOL_CMP_AND = 358
};

class token {
public:
    token();

    token_type type = TOKEN_UNDEFINED;
    std::string value = "";

    int lineNumber = 0;
    std::string fileName = "";

public:
    token(token_type type, std::string value, int lineNumber, std::string fileName);
};


#endif //TESTPROJECT_TOKEN_H
